language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.2
  - android-24
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle