language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.2
  - android-24
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - '.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install:
  - mkdir "$HOME/android/licenses" || true
  - echo -e "\ne6b7c2ab7fa2298c15165e9583d0acf0b04a2232" > "$HOME/android/licenses/android-sdk-license"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$HOME/android/licenses/android-sdk-license"
  - echo -e "\n504667f4c0de7af1a06de9f4b1727b84351f2910" > "$HOME/android/licenses/android-sdk-preview-license"